name: Save my streak
on:
  schedule:
    - cron: '11 * * * *' # Run at 11:* every day
  push:
    branches:
      - dev
jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Create .env file
        run: |
          cat > .env << EOF
          CAPTCHA_API_KEY=${{ secrets.CAPTCHA_API_KEY }}
          TIKTOK_USERNAME=${{ secrets.TIKTOK_USERNAME }}
          TIKTOK_PASSWORD=${{ secrets.TIKTOK_PASSWORD }}
          MESSAGE=${{ secrets.MESSAGE }}
          TIKTOK_FRIEND_USERNAME=${{ secrets.TIKTOK_FRIEND_USERNAME }}
          EOF

      - name: Run the script
        run: python main.py